apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: target-app
    system: autofixops
  name: autofixops-target-app
  namespace: autofixops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-app
      system: autofixops
  template:
    metadata:
      labels:
        app: target-app
        prometheus.io/port: '8000'
        prometheus.io/scrape: 'true'
        system: autofixops
    spec:
      containers:
      - image: autofixops/target-app:latest
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        name: target-app
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 64Mi
